заглушки-блоки для админ панели(хедер, футер)
ForexPro117/MedSite pull request #4
Opened 2021-11-14 15:41 UTC by UndFrame

2021-11-14 17:50 UTC, ametr1ne commented
d

2021-11-16 13:35 UTC, ForexPro117 requested changes
site-app/public/images/bg.jpg - неправильно
site-app/public/storage/images/bg.jpg - правильно

2021-11-16 13:35 UTC, ForexPro117 commented on site-app/resources/views/blocks/admin_panel_footer.blade.php
> +  </footer>
по макету у тебя нет футера, хедер ты можешь располагать отдельно и потом вызвать отдельно через @extend @content

2021-11-16 13:35 UTC, ForexPro117 commented on site-app/resources/views/blocks/admin_panel_header.blade.php
> +<header class="p-3 text-white" >
Ну тут тоже не по макету

2021-12-09 11:42 UTC, closed without merging